data:
  image_root: "dataset"
  train_annotation_file: "dataset/train_label.xlsx"
  test_annotation_file: "dataset/test_label.xlsx"
  img_size: (224, 224)
model:
  model_name: 'vit_large_patch14_clip_224.openai'
  pretrained: True
  num_classes: 10
  lora_cfg:
    r: 64
    alpha: 32
    dropout: 0.1
    target_modules: '.*\.qkv|.*\.fc\d|.*\.proj|proj|stem_0'
optimizer:
  lr: 0.0005

  
